@extends('layouts.static')

@section('content')

    <div class="top-container">
        <h2 class="footer-page-headline">
            <div class="container">
                <div class="col col-sm-offset-2 col-sm-10">Our Terms</div>
            </div>
        </h2>
    </div>
    <div class="container">
        <div class="col col-sm-3 col-md-2">
            <div class="side-links-menu">
                <ul class="list-unstyled clearfix">
                    <li><a href="{{ url('privacy') }}">Privacy</a></li>
                    <li class="active"><a href="{{ url('terms') }}">Terms</a></li>
                    <li><a href="{{ url('contact') }}">Contact</a></li>
                    <li ><a href="{{ url('join') }}">Join as Advisor</a></li>
                </ul>
            </div>
        </div>
        <div class="col col-sm-9 col-md-10">
            <div class="bottom-container">
                <p style="text-align: center;"><strong>For Questions or Support, Please Call: 1-866-994-5907</strong></p>

                <p style="text-align: center;"><strong>​ Live Cosmos LLC Terms and Conditions</strong></p>

                <p style="text-align: center;">Last Revised August 2nd, 2016</p>

                <p style="text-align: center;"><em>Welcome to Live Cosmos LLC Terms and Conditions Agreement. </em></p>

                <p>This is a legal agreement between you and Live Cosmos LLC, DBA, livecosmos.com hereinafter referred to as &ldquo;live cosmos&rdquo;. If Live Cosmos accepts your registration form you will become a &quot;User&quot; having access to the Site and Advisor and Astrology Services only under the policies, terms and conditions below:</p>

                <p>YOU UNDERSTAND THAT BY CLICKING THE BUTTON TO CONTINUE ON THE REGISTRATION PAGE, BY USING THE SITE (AS DEFINED BELOW) AND ANY ADVISOR SERVICES (AS DEFINED BELOW) INCLUDING ANY CONTENT PROVIDED THEREIN, BY INITIATING ANY FORM OF COMMUNICATION WITH A User, OR BY POSTING ANY LISTINGS ON THIS SITE, YOU ARE AGREEING TO BE BOUND BY THIS User AGREEMENT AND YOU ARE BOUND IN THE SAME WAY THAT A PAPER CONTRACT BINDS YOU. ALL USE OF THE SITE AND ADVISOR SERVICES IS SUBJECT TO THE TERMS OF THIS User AGREEMENT AND THE POLICIES, RULES, TERMS AND INSTRUCTIONS ON THE SITE OR INCORPORATED HEREIN ARE PART OF THIS User AGREEMENT. YOU MUST ACCEPT WITHOUT MODIFICATION ALL OF THE TERMS, CONDITIONS, POLICIES AND NOTICES REFERENCED IN THIS User AGREEMENT IN ORDER TO ACCESS AND USE THE SITE AND ADVISOR SERVICES. IF YOU DO NOT ACCEPT THIS User AGREEMENT IN ITS ENTIRETY, YOU MAY NOT ACCESS OR USE THE SITE OR ADVISOR SERVICES.</p>

                <p>The policies, terms and conditions below limit Live cosmos&#39;s liability and obligations to you and allow Live cosmos to change, suspend or terminate your access to and use of the livecosmos.com and any services any time in Live cosmos&#39;s sole discretion. We strongly urge you to carefully read the following terms and conditions, and all policies referenced below or elsewhere on the Site. The following policies and rules are incorporated into this terms and conditions Agreement.</p>

                <p><u>1. Eligibility to Use of Site aka livecosmos.com </u></p>

                <p>Registration to livecosmos.com is for persons who are at least 18 years old of age or 21 in some regions and are capable of forming a legally binding contract under applicable law. Live Cosmos reserves the right to suspend services to any users at its own sole discretion. Under no circumstance should you use this site if your use is prohibited by the trade laws of the United States or any other country.</p>

                <p><u>2. Chat and Consult with Advisors at your Own Risk.</u></p>

                <p>Live Cosmos does not evaluate, provides, controls, or govern the chat and advisor services between You and the Advisor. All registered Advisors are verified by a third party. Live Cosmos does not provide any advice, information, entertainment services, or any other form of user exchanged chats. Live Cosmos does not guarantee or verifies or represents any of the chat advisors. held responsible for any Advisor&#39;s failure to comply with laws or regulations concerning the content of listings. Instead, Live cosmos acts as a technology service that allows Users to share advice, information and other products or services among themselves. Although Live cosmos helps its Users connect with each other, it does not monitor the advice exchanged, and, as a result, Live cosmos does not control, nor is it responsible for, the truth, accuracy, completeness, safety, timeliness, quality, appropriateness, legality or applicability of anything said or written by Users, including without limitation any information contained in Advisor listings or made available through livecosmos.com Livecosmos.com is not intended for use as a payment service to exchange goods. Live cosmos is not responsible for the use or exchange of any information, files or goods between Users. You are solely responsible for, and will exercise caution, discretion, common sense and judgment in, using livecosmos.com and chat advisors, in evaluating the qualifications of, and statements made by chat advisors. Live cosmos prohibits disclosure of personal contact information to other Users, including chat advisors. If you do, you do so at your own risk. Placement of a User in a particular category does not mean that they are qualified in any such area or category. Live cosmos assumes no responsibility for monitoring any User feedback or otherwise policing its users in any way. If you ever believe that a user or chat advisor has violated the law or is defrauding, threatening or endangering anyone, Live cosmos urges you to immediately contact the police directly for help. In addition, Live cosmos prohibits users from using livecosmos.com or chat advice services to solicit other users to meet with them in person. If you decides to meet and/or share any personal information with any other user at livecosmos.com, you do so at your own risk.</p>

                <p><u>3. Verification of Services Provided </u></p>

                <p>Live cosmos does not refer, endorse, recommend, verify, evaluate or guarantee any advice, information, entertainment services or other products or services provided by chat advisors or users, or any specific user, chat advisor, and nothing shall be considered as a referral, endorsement, recommendation or guarantee of any chat advisor Live cosmos. You must use your own judgment to determine whether to initiate, receive and/or discontinue use of the chat advice services. Users who initiate, receive and/or discontinue use of the chat advices services do so entirely at their own risk, and Live cosmos bears no responsibility in this regard. In accordance with its Privacy Policy, Live cosmos does not monitor live chat conversations between users. However, Live cosmos reserves the right to monitor any chat conversations, and email conversations between users in order to evaluate compliance with the rules and policies set forth in this terms and conditions agreement and to take other action as set forth in the Privacy Policy. Therefore, we urge you to review and understand the Privacy Policy. As part of this terms and conditions you are agreeing to the terms and conditions set forth in the Privacy Policy and are obliged to abide by its terms.</p>

                <p><u>4. Disputes</u></p>

                <p>If you have a dispute with another User, or suffer any harm arising out of or connected with any chat advisor services, you hereby waive all claims against and release Live Cosmos (and its parents, subsidiaries, employees, officers, directors, shareholders, suppliers, joint venturers and agents) from any and all liability for claims, demands, damages (actual and consequential), costs and expenses (including litigation costs and attorneys&#39; fees) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with any chat advisor services or with regard to such disputes. If you are a California resident, you waive your rights under California Civil Code &sect; 1542, which states, &quot;A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR&quot; Residents of other states and jurisdictions waive their rights under analogous laws, statutes or regulations.</p>

                <p><u>5. Chat Advisors Responsibility </u></p>

                <p>Live cosmos acts only as a connector for communications initiated between Users and as a third party payment network. As a chat advisor, you are not an employee, agent or contractor of Live cosmos, and you shall not represent that you are any of the foregoing. You are solely responsible for all equipment necessary to access and use of livecosmos.com and chat advisor services, and for reporting and payment of all taxes associated with fees transferred to you by Live cosmos. Live cosmos accepts no responsibility for reporting to law enforcement agencies any threats made by users to harm themselves or third parties or take any illegal action. Any such responsibility lies with the chat advisor. By providing chat advice, you agree to: A. Comply with all of Live Cosmos standards and requirements. Including, but not limited to: software training, language used, availability and quality of content. B. You agree that you will be the only user accessing your account and its settings C. You agree to maintain your account with complete confidently of your password and user account information and to supervise all activities that occur under your Member name, password or Member account, including, but not limited to, any and all usage of livecosmos.com by other persons under your Member name and password. You agree that you will not permit, enable, introduce or facilitate (i) non-Members to have access to or use of the Site or chat advice services in any manner without first becoming Members and (ii) simultaneous use of chat advice services by others with you. D. You agree that you are responsible for content provided. E. You agree not to store, and/or record any of the chats on livecosmos.com F. You will not use the live cosmos for any purpose that is, or depict any content that is, unlawful, fraudulent. G. You will never, and under no circumstance provide any advice directly or in directly, involving investing in, purchasing or selling stocks/securities/bonds, or any other financial services or advice related. H. You will not use Live Cosmos to transmit any: unlawful, harassing, libelous, privacy invading, abusive, threatening, defamatory, vulgar, obscene, racist, harmful, or otherwise objectionable communications or material of any kind. I. You will never under not circumstance try to gain personal information from users. J. You will not use Live Cosmos to promote prizes, games, or any unrelated material other then what is approved by Live Cosmos. K. You will comply and adhere to all applicable laws and regulations governing your actions in connection with Live Cosmos. L. You will never share any information gained or received through livecosmos.com M. You agree to comply with this terms and conditions, live cosmos privacy policy and live chat</p>

                <p><u>6. Modification to Terms and Conditions &amp; Site Access</u></p>

                <p>Live cosmos reserves the right in its sole discretion and without notice to modify or discontinue livecosmos.com services and/or modify the terms and conditions of this Agreement and incorporated rules and policies, and you agree to be bound by any such modifications. Any modifications will be effective immediately. We may choose to notify you by email regarding significant modifications. If any modification of this agreement is not agreeable by you, your only recourse is to cease using livecosmos.com and chat services. By continuing to use of livecosmos.com any chat services following any posting of a new terms and conditions agreement or policies on livecosmos.com, you accept and agree to be bound by the new terms and conditions agreement or policies. Live Cosmos reserves the right to suspend and/or terminate any user&rsquo;s membership and refuse to provide or allow access to livecosmos.com and its data without notice or reason. Live Cosmos reserves the right to notify authorities and/or banks to take actions against you without notice if you A. failed to comply with this terms and conditions agreement. B. Live Cosmos is unable to verify you and your billing information. C. If live cosmos suspects you may be involved in illegal activities that may harm anyone. As a Live Cosmos user you agree that you will never record, copy or store information received on livecosmos.com unless otherwise provided to you by live cosmos.</p>

                <p><u>7. Pricing &amp; Refunds</u></p>

                <p>You acknowledge and agree that Live cosmos reserves the right to charge for access to the Website and use of its chat services. Live cosmos RESERVES THE RIGHT, IN Live cosmos&#39;S SOLE DISCRETION, TO CHANGE THE FEES AND CHARGES IN EFFECT, OR TO ADD NEW FEES AND CHARGES, BY POSTING SUCH CHANGES ON THE WEBSITE OR PROVIDING NOTICE TO YOU. REFUNDS ARE HANDLED ON A CASE-BY-CASE BASIS AND IF YOU ARE EVER NOT SATISFIED WITH OUR SERVICES PLEASE FREE TO CALL US AT 1-866-994-5907 AND WE WILL ADDRESS YOUR CONCERNS. Live cosmos&#39;s decision not to exercise any specific right or require performance of any specific obligation under this Agreement, including without limitation the collection of monthly or regular fees from You, shall not affect Live cosmos&#39;s subsequent ability to exercise such right or require such performance at any time thereafter. Nor shall Live cosmos&#39;s waiver of Your breach constitute Live cosmos&#39;s waiver of any subsequent breach. By opting for membership or paid services, You authorize Live cosmos, and/or its payment processor, to charge these fees to the credit card, debit card, or other payment method you provide, in addition to applicable sales taxes and other taxes. In exchange for chat services (minute packages), Live Cosmos shall charge a package fee for chat conversations of $29.95 for 5 minutes, $39.95 for 10 minutes and $44.25 for 15 minutes. To discuss refunds, please contact customer service at the number listed below. All your payments are tracked and are available within your account at http:// www.livecosmos.com You may contact Live Cosmos support at any time: 1-866-994-5907</p>

                <p><u>8. Third Party Websites</u></p>

                <p>The Website is linked with the websites of third parties (&quot;Third-Party Websites&quot;), some of whom may have established relationships with Live cosmos and some of whom may not. Live cosmos does not have control over the content and performance of Third-Party Websites. Live cosmos has not reviewed, and cannot review or control, all of the material, including computer software or other goods or services, made available on or through third-party websites. Accordingly, Live cosmos does not represent, warrant, or endorse any third-party website, or the accuracy, currency, content, fitness, lawfulness, or quality of the information, material, goods, or services available through third-party websites. Live cosmos disclaims, and you agree to assume, all responsibility and liability for any damages or other harm, whether to you or to third parties, resulting from your use of third-party websites.</p>

                <p><u>9. Copy Rights</u></p>

                <p>All content and other materials available through the Website and Services, including without limitation the Live cosmos logo, design, text, graphics, and other files, and the selection, arrangement, and organization thereof, are either owned by Live cosmos, LLC or are the property of Live cosmos&#39;s licensors and suppliers. Except as explicitly provided, neither Your use of the Website and Services nor this Agreement grant You any right, title, or interest in or to any such materials. live cosmos and the &quot;Live cosmos logo&quot; (collectively, the &quot;Live cosmos Marks&quot;) are trademarks or registered trademarks of Live cosmos, LLC. Other trademarks, service marks, graphics, logos, and domain names appearing on the Website may be the trademarks of third-parties. Neither Your use of the Website and Services nor this Agreement grant You any right, title or interest in or to, or any license to reproduce or otherwise use, the Live cosmos Marks or any third-party trademarks, service marks, graphics, logos or domain names. You agree that any goodwill in the Live cosmos Marks generated as a result of Your use of the Website and Services will inure to the benefit of Live cosmos, LLC, and You agree to assign, and hereby do assign, all such goodwill to Live cosmos, LLC. You shall not at any time, nor shall You assist others to, challenge Live cosmos, LLC&#39;s right, title, or interest in or to, or the validity of, the Live cosmos Marks.</p>

                <p><u>11. Privacy Policy</u></p>

                <p>By using the Website, You consent to the collection and use of certain information about You, as specified in the Privacy Policy. Live cosmos encourages users of the Website to frequently check Live cosmos&#39;s Privacy Policy for changes.</p>

                <p><u>12. Arbitration</u></p>

                <p>If You and Live cosmos cannot resolve a Claim through negotiations, either party may elect to have the Claim finally and exclusively resolved by binding arbitration. Any election to arbitrate by one party shall be final and binding on the other(s). YOU HEREBY ACKNOWLEDGE THAT WITHOUT THIS PROVISION, YOU WOULD HAVE THE RIGHT TO SUE IN COURT WITH A JURY TRIAL OR TO PARTICIPATE IN A CLASS ACTION. The language in this Agreement shall be interpreted in accordance with its fair meaning and not strictly for or against either party. The arbitration shall be commenced and conducted under the Commercial Arbitration Rules of the American Arbitration Association (&quot;AAA&quot;), as modified by this Agreement, available at the AAA website www.adr.org or by calling the AAA at 1-800-778-7879. Except as otherwise provided for herein, Live cosmos will pay the AAA filing, administration, and arbitrator fees. If, however, the arbitrator finds that either the substance of your claim or the relief sought is frivolous or brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedures 11(b)), then the payment of all such fees will be governed by the AAA Rules. In that case, You hereby agree to reimburse Live cosmos for all payments disbursed that are your obligation to reimbursed under the AAA Rules. If you are unable to pay the arbitration fee, Live cosmos will pay it directly upon receiving a written request and a sworn statement that you are unable to pay. The arbitrator is bound by the terms of this Agreement. All issues are for the arbitrator to resolve, except that issues relating to the enforceability of the arbitration provision for a Court of Competent Jurisdiction to resolve. The arbitration may be conducted in person, through document submission, through telephone, or online. The arbitrator will issue a decision in writing, but need only provide a statement of reasons if requested by a party. The arbitrator must follow applicable law, and any award may be challenged if the arbitrator fails to do so. Live cosmos may litigate to compel arbitration in court, to stay proceedings pending arbitration, or to modify, confirm, vacate, or enter judgment on the award entered by the Copy Right 2016 Live Cosmos LLC</p>
            </div>
        </div>
    </div>
@endsection